name: Generate Changelog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main #casaaaaa

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install conventional-changelog-cli
        run: npm install -g conventional-changelog-cli

      - name: Generate or update CHANGELOG.md
        run: |
          if [ -f CHANGELOG.md ]; then
            echo "Updating existing CHANGELOG.md..."
            conventional-changelog -p angular -i CHANGELOG.md -s -r 0
          else
            echo "Creating new CHANGELOG.md..."
            conventional-changelog -p angular -o CHANGELOG.md -r 0
          fi

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "docs: update CHANGELOG.md" || echo "No changes to commit"
          git push