name: Generate Changelog

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**' #here things get weirdddss

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install standard-version globally
        run: npm install -g standard-version

      - name: Configure Git identity
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Run standard-version
        run: npx standard-version

      - name: Push version bump and changelog
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          git push --follow-tags origin "$current_branch"
