name: Version & Changelog

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # N

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --save-dev standard-version

      - name: Bump version & generate changelog
        run: npx standard-version

      - name: Commit & push version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git push --follow-tags origin ${{ github.ref_name }}